In [12]:
import feedparser
import json
import re
from datetime import datetime, timedelta
import time
import pandas as pd


keywords = ["ai","artificial intelligence", "machine learning", "robot", "robots"]


# add other rss for other big news outlets itv, sky, maybe as well things like real python
urls = ["https://www.theguardian.com/uk/technology/rss",
        "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
        "https://www.marktechpost.com/feed/",
        "https://www.wired.com/feed/rss",
        #"https://www.wired.com/feed/tag/ai/latest/rss"
        "https://openai.com/blog/rss/",
        "https://news.microsoft.com/source/topics/ai/feed/",
        "https://feeds.bbci.co.uk/news/technology/rss.xml"
        ]


# regex pattern with word boundaries for all keywords
pattern = re.compile(r'\b(' + '|'.join(map(re.escape, keywords)) + r')\b', re.IGNORECASE)

cutoff = datetime.now() - timedelta(days=3)

all_results = []  # <-- master container

for url in urls:
    feed = feedparser.parse(url)
    top_ten = feed.entries[:15]
    feed_results = []


    for e in top_ten:
        if "published_parsed" not in e:
            continue

        pub_date = datetime.fromtimestamp(time.mktime(e.published_parsed))
        print(pub_date)

        if pub_date > cutoff and (pattern.search(e.title or "") or pattern.search(e.summary or "")):
            feed_results.append({
                "title": e.title,
                "link": e.link,
                "published": e.published,
                "summary": e.get("summary", ""),
                "source": feed.feed.get("title", url)
            })

    if feed_results:
        #all_results[url] = feed_results
        all_results.extend(feed_results)

# Output one piece of JSON
json_output = json.dumps(all_results, indent=2)
print(json_output)
print(len(all_results))

2026-01-14 07:00:19
2026-01-13 19:03:16
2026-01-13 20:14:42
2026-01-14 10:00:23
2026-01-13 13:58:43
2026-01-13 05:00:27
2026-01-12 17:14:52
2026-01-14 10:00:11
2026-01-13 20:15:05
2026-01-13 10:00:00
2026-01-12 07:00:48
2025-10-30 07:00:55
2025-10-22 07:00:59
2025-10-15 07:00:16
2025-10-08 07:00:18
2026-01-14 04:40:32
2026-01-12 22:35:16
2026-01-12 21:23:30
2026-01-13 12:00:03
2026-01-13 16:21:57
2026-01-12 22:25:24
2026-01-12 10:02:11
2026-01-12 22:50:16
2026-01-10 05:00:05
2026-01-09 16:26:13
2026-01-09 17:29:32
2026-01-09 20:48:03
2026-01-09 16:47:29
2026-01-08 22:11:49
2026-01-08 21:05:47
2026-01-14 07:30:39
2026-01-13 15:24:46
2026-01-13 14:37:15
2026-01-13 14:12:20
2026-01-13 04:25:07
2026-01-12 17:05:08
2026-01-11 15:47:06
2026-01-11 15:12:24
2026-01-09 15:47:26
2026-01-09 14:50:15
2026-01-14 10:30:00
2026-01-14 10:00:00
2026-01-14 06:30:00
2026-01-14 06:10:00
2026-01-14 06:00:00
2026-01-13 23:47:17
2026-01-13 20:00:00
2026-01-13 18:59:02
2026-01-13 18:54:50
2026-01-13 18:44:50
2026-01-13 18:27:24
2026-01-13 16:45:19
2026-01-13 14:48:07
2026-01-13 13:00:00
2026-01-13 12:00:00
2026-01-08 14:36:51
2026-01-07 15:14:55
2025-12-19 16:07:02
2025-12-18 17:04:49
2025-12-18 15:33:36
2025-12-17 16:09:38
2025-12-12 13:36:54
2025-12-11 14:03:29
2025-12-10 14:03:43
2025-12-09 17:14:45
2026-01-14 00:07:50
2026-01-13 17:35:04
2026-01-13 13:09:19
2026-01-12 19:38:53
2026-01-13 03:34:43
2026-01-12 16:11:02
2026-01-12 14:27:52
2026-01-12 00:07:23
2026-01-12 05:21:33
2026-01-11 00:38:32
2026-01-09 21:41:19
2026-01-08 17:14:32
2026-01-08 16:33:44
2026-01-08 08:03:50
2026-01-08 09:58:38
[
  {
    "title": "Musk v Starmer: will UK ban X over Grok nudification? | The Latest",
    "link": "https://www.theguardian.com/technology/video/2026/jan/13/musk-v-starmer-will-uk-ban-x-over-grok-nudification-the-latest",
    "published": "Tue, 13 Jan 2026 19:03:16 GMT",
    "summary": "<p>The UK government is threatening Elon Musk\u2019s X with a ban. The social media platform is under pressure from ministers over the use of the Grok AI tool to manipulate images of women and children to remove their clothes.&nbsp;Ofcom, the UK\u2019s media regulator, has launched an investigation into X \u2013 and the government says it will support a ban if Ofcom decides to press ahead.</p> <a href=\"https://www.theguardian.com/technology/video/2026/jan/13/musk-v-starmer-will-uk-ban-x-over-grok-nudification-the-latest\">Continue reading...</a>",
    "source": "Technology | The Guardian"
  },
  {
    "title": "Use of AI to harm women has only just begun, experts warn",
    "link": "https://www.theguardian.com/technology/2026/jan/14/use-of-ai-to-harm-women-has-only-just-begun-experts-warn",
    "published": "Wed, 14 Jan 2026 10:00:23 GMT",
    "summary": "<p>While Grok has introduced belated safeguards to prevent sexualised AI imagery, other tools have far fewer limits</p><p>\u201cSince discovering Grok AI, regular porn doesn\u2019t do it for me anymore, it just sounds absurd now,\u201d one enthusiast for the Elon Musk-owned AI chatbot wrote on Reddit. Another agreed: \u201cIf I want a really specific person, yes.\u201d</p><p>If those who have been <a href=\"https://www.theguardian.com/technology/2026/jan/05/elon-musk-grok-ai-digitally-undress-images-of-women-children\">horrified by the distribution of sexualised imagery on Grok</a> hoped that last week\u2019s <a href=\"https://www.theguardian.com/technology/2026/jan/09/grok-image-generator-outcry-sexualised-ai-imagery\">belated safeguards</a> could put the genie back in the bottle, there are many such posts on Reddit and elsewhere that tell a different story.</p> <a href=\"https://www.theguardian.com/technology/2026/jan/14/use-of-ai-to-harm-women-has-only-just-begun-experts-warn\">Continue reading...</a>",
    "source": "Technology | The Guardian"
  },
  {
    "title": "Google parent Alphabet hits $4tn valuation after AI deal with Apple",
    "link": "https://www.theguardian.com/technology/2026/jan/12/google-gemini-alphabet-4-trillion-value",
    "published": "Mon, 12 Jan 2026 17:14:52 GMT",
    "summary": "<p>After Apple chose Gemini to power Siri, Alphabet surpassed Apple to become second-most valuable company in world</p><p><a href=\"https://www.theguardian.com/technology/google\">Google</a>\u2019s parent company hit a major financial milestone on Monday, reaching a $4tn valuation for the first time and surpassing Apple to become the second-most valuable company in the world.</p><p><a href=\"https://www.theguardian.com/technology/alphabet\">Alphabet</a> is the fourth company to hit the $4tn milestone after <a href=\"https://www.theguardian.com/technology/2025/jul/09/nvidia-first-company-4-trillion\">Nvidia</a>, which <a href=\"https://www.theguardian.com/technology/2025/oct/29/nvidia-first-company-5-trillion\">later hit $5tn</a>, <a href=\"https://www.theguardian.com/technology/2025/jul/31/microsoft-valuation-ai-boom\">Microsoft</a> and <a href=\"https://www.theguardian.com/technology/2025/oct/28/apple-market-value-iphone\">Apple</a>.</p> <a href=\"https://www.theguardian.com/technology/2026/jan/12/google-gemini-alphabet-4-trillion-value\">Continue reading...</a>",
    "source": "Technology | The Guardian"
  },
  {
    "title": "The best air fryers in the UK, tried and tested for crisp and crunch",
    "link": "https://www.theguardian.com/thefilter/2025/mar/02/best-air-fryers",
    "published": "Wed, 14 Jan 2026 10:00:11 GMT",
    "summary": "<p>Air fryers have taken over our kitchens, but which wins the crown for the crispiest cooking? Our expert peeled 7kg of potatoes to find out</p><p>\u2022 <a href=\"https://www.theguardian.com/thefilter/2025/jan/07/best-blenders\"><strong>The best blenders to blitz like a pro, tried and tested</strong></a></p><p>Air fryers inspire the sort of feelings that microwaves did in the 1980s. I vividly remember those new-fangled boxes being spoken about often, either dismissively or with delight. A rash of cookbooks followed, and dinner changed across the land. Fast-forward a few decades, and air fryers have become the same kind of kitchen \u201cdisruptors\u201d, offering time-saving convenience and healthier cooking, but with the added allure of easily achieved, mouth-watering crispiness.</p><p>Since launching with a single-drawer design, air fryers have evolved. Sizes range from compact to XL, while drawer configurations can be double, split or stacked. Alongside air frying, many will grill, roast and bake, and some will dip to lower temperatures for dehydrating, fermenting and proving dough. One we tested features steam cooking, allowing you to whip up dim sum as easily as a roast dinner, while another included racks for cooking on four levels.</p><p><strong>Best air fryer overall</strong><strong>:</strong> <br />\n Tefal Easy Fry Dual XXL EY942BG0</p><p><strong>Best budget air fryer:<br /></strong>Tower AirX AI Digital Air Fryer</p> <a href=\"https://www.theguardian.com/thefilter/2025/mar/02/best-air-fryers\">Continue reading...</a>",
    "source": "Technology | The Guardian"
  },
  {
    "title": "The five new gadgets I tried and loved at CES 2026 (that you can buy right now)",
    "link": "https://www.theguardian.com/thefilter-us/2026/jan/13/consumer-electronics-show-gadgets",
    "published": "Tue, 13 Jan 2026 20:15:05 GMT",
    "summary": "<p>From smartglasses to nano phone chargers, these futuristic products from the Consumer Electronics Show are available right away</p><ul><li><p><a href=\"https://www.theguardian.com/thefilter-us/2025/oct/20/best-travel-gadgets\">I\u2019m a digital nomad who works on the road. These seven travel gadgets go with me everywhere</a></p></li></ul><p>Every year, the Consumer Electronics Show (CES) gives us a glimpse of what\u2019s around the corner in <a href=\"https://www.theguardian.com/us/technology\">tech</a>: creepy humanoid robots, robovacs that climb stairs, AI baked into everything.</p><p>Some of these products will never come to fruition. Some will arrive months later. And some \u2013 the rarities we picked out below \u2013 are available to order right now. I had a chance to try each one in person on the show floor in Las Vegas. So if you\u2019re looking for a taste of the future today, here\u2019s your fix.</p> <a href=\"https://www.theguardian.com/thefilter-us/2026/jan/13/consumer-electronics-show-gadgets\">Continue reading...</a>",
    "source": "Technology | The Guardian"
  },
  {
    "title": "Meta Plans to Cut 10% to 15% of Employees in Reality Labs Business",
    "link": "https://www.nytimes.com/2026/01/12/technology/meta-layoffs-reality-labs.html",
    "published": "Mon, 12 Jan 2026 22:35:16 +0000",
    "summary": "The layoffs are set to be announced this week and would affect Meta\u2019s work on the metaverse, as the company spends heavily on building artificial intelligence.",
    "source": "NYT > Technology"
  },
  {
    "title": "Apple Teams Up With Google for A.I. in Its Products",
    "link": "https://www.nytimes.com/2026/01/12/technology/apple-google-ai-partnership.html",
    "published": "Mon, 12 Jan 2026 21:23:30 +0000",
    "summary": "Apple was facing increasing questions about its plans for artificial intelligence as other big tech companies invested tens of billions in the technology.",
    "source": "NYT > Technology"
  },
  {
    "title": "Google AI Releases MedGemma-1.5: The Latest Update to their Open Medical AI Models for Developers",
    "link": "https://www.marktechpost.com/2026/01/13/google-ai-releases-medgemma-1-5-the-latest-update-to-their-open-medical-ai-models-for-developers/",
    "published": "Wed, 14 Jan 2026 07:30:39 +0000",
    "summary": "<p>Google Research has expanded its Health AI Developer Foundations program (HAI-DEF) with the release of MedGemma-1.5. The model is released as open starting points for developers who want to build medical imaging, text and speech systems and then adapt them to local workflows and regulations. MedGemma 1.5, small multimodal model for real clinical data MedGemma [&#8230;]</p>\n<p>The post <a href=\"https://www.marktechpost.com/2026/01/13/google-ai-releases-medgemma-1-5-the-latest-update-to-their-open-medical-ai-models-for-developers/\">Google AI Releases MedGemma-1.5: The Latest Update to their Open Medical AI Models for Developers</a> appeared first on <a href=\"https://www.marktechpost.com\">MarkTechPost</a>.</p>",
    "source": "MarkTechPost"
  },
  {
    "title": "Understanding the Layers of AI Observability in the Age of LLMs",
    "link": "https://www.marktechpost.com/2026/01/13/understanding-the-layers-of-ai-observability-in-the-age-of-llms/",
    "published": "Tue, 13 Jan 2026 14:37:15 +0000",
    "summary": "<p>Artificial intelligence (AI) observability refers to the ability to understand, monitor, and evaluate AI systems by tracking their unique metrics\u2014such as token usage, response quality, latency, and model drift. Unlike traditional software, large language models (LLMs) and other generative AI applications are probabilistic in nature. They do not follow fixed, transparent execution paths, which makes [&#8230;]</p>\n<p>The post <a href=\"https://www.marktechpost.com/2026/01/13/understanding-the-layers-of-ai-observability-in-the-age-of-llms/\">Understanding the Layers of AI Observability in the Age of LLMs</a> appeared first on <a href=\"https://www.marktechpost.com\">MarkTechPost</a>.</p>",
    "source": "MarkTechPost"
  },
  {
    "title": "Google AI Releases Universal Commerce Protocol (UCP): An Open-Source Standard Designed to Power the Next Generation of Agentic Commerce",
    "link": "https://www.marktechpost.com/2026/01/12/google-ai-releases-universal-commerce-protocol-ucp-an-open-source-standard-designed-to-power-the-next-generation-of-agentic-commerce/",
    "published": "Tue, 13 Jan 2026 04:25:07 +0000",
    "summary": "<p>Can AI shopping agents move beyond sending product links and actually complete trusted purchases end to end inside a chat? Universal Commerce Protocol, or UCP, is Google\u2019s new open standard for agentic commerce. It gives AI agents and merchant systems a shared language so that a shopping query can move from product discovery to an [&#8230;]</p>\n<p>The post <a href=\"https://www.marktechpost.com/2026/01/12/google-ai-releases-universal-commerce-protocol-ucp-an-open-source-standard-designed-to-power-the-next-generation-of-agentic-commerce/\">Google AI Releases Universal Commerce Protocol (UCP): An Open-Source Standard Designed to Power the Next Generation of Agentic Commerce</a> appeared first on <a href=\"https://www.marktechpost.com\">MarkTechPost</a>.</p>",
    "source": "MarkTechPost"
  },
  {
    "title": "Meet SETA: Open Source Training Reinforcement Learning Environments for Terminal Agents with 400 Tasks and CAMEL Toolkit",
    "link": "https://www.marktechpost.com/2026/01/11/meet-seta-open-source-training-reinforcement-learning-environments-for-terminal-agents-with-400-tasks-and-camel-toolkit/",
    "published": "Sun, 11 Jan 2026 15:12:24 +0000",
    "summary": "<p>What does an end to end stack for terminal agents look like when you combine structured toolkits, synthetic RL environments, and benchmark aligned evaluation? A team of researchers from CAMEL AI, Eigent AI and other collaborators have released SETA, a toolkit and environment stack that focuses on reinforcement learning for terminal agents. The project targets [&#8230;]</p>\n<p>The post <a href=\"https://www.marktechpost.com/2026/01/11/meet-seta-open-source-training-reinforcement-learning-environments-for-terminal-agents-with-400-tasks-and-camel-toolkit/\">Meet SETA: Open Source Training Reinforcement Learning Environments for Terminal Agents with 400 Tasks and CAMEL Toolkit</a> appeared first on <a href=\"https://www.marktechpost.com\">MarkTechPost</a>.</p>",
    "source": "MarkTechPost"
  },
  {
    "title": "Roblox\u2019s AI-Powered Age\u00a0Verification Is a Complete Mess",
    "link": "https://www.wired.com/story/robloxs-ai-powered-age-verification-is-a-complete-mess/",
    "published": "Tue, 13 Jan 2026 18:54:50 +0000",
    "summary": "Kids are being identified as adults\u2014and vice versa\u2014on Roblox, while age-verified accounts are already being sold online.",
    "source": "WIRED"
  },
  {
    "title": "Honey, I shrunk the data centres: Is small the new big?",
    "link": "https://www.bbc.com/news/articles/cd0ynenr1eno?at_medium=RSS&at_campaign=rss",
    "published": "Wed, 14 Jan 2026 00:07:50 GMT",
    "summary": "Huge data centres are being built to handle AI computing but some experts say they aren't necessary.",
    "source": "BBC News"
  },
  {
    "title": "Apple turns to Google to power AI upgrade for Siri",
    "link": "https://www.bbc.com/news/articles/czdqvp2zqezo?at_medium=RSS&at_campaign=rss",
    "published": "Tue, 13 Jan 2026 13:09:19 GMT",
    "summary": "Analysts say the deal is likely to be welcomed by consumers - but reflects Apple's failure to develop its own AI tools.",
    "source": "BBC News"
  },
  {
    "title": "What a new law and an investigation could mean for Grok AI deepfakes",
    "link": "https://www.bbc.com/news/articles/ckgvx88md4do?at_medium=RSS&at_campaign=rss",
    "published": "Mon, 12 Jan 2026 19:38:53 GMT",
    "summary": "Elon Musk's chatbot is under fire for altering images of women to remove their clothes without their consent.",
    "source": "BBC News"
  },
  {
    "title": "Ofcom investigates Elon Musk's X over Grok AI sexual deepfakes",
    "link": "https://www.bbc.com/news/articles/cwy875j28k0o?at_medium=RSS&at_campaign=rss",
    "published": "Mon, 12 Jan 2026 14:27:52 GMT",
    "summary": "The watchdog said it had received reports of the platform's Grok AI chatbot creating undressed images of people.",
    "source": "BBC News"
  },
  {
    "title": "Eggie, Neo, Isaac and Memo are domestic robots. But would you let them load your dishwasher?",
    "link": "https://www.bbc.com/news/articles/clyg63e3mq4o?at_medium=RSS&at_campaign=rss",
    "published": "Mon, 12 Jan 2026 00:07:23 GMT",
    "summary": "Joe Tidy meets robots being trained to tidy up all your mess.",
    "source": "BBC News"
  }
]
17

In [13]:
print(feed_results)

[{'title': 'Honey, I shrunk the data centres: Is small the new big?', 'link': 'https://www.bbc.com/news/articles/cd0ynenr1eno?at_medium=RSS&at_campaign=rss', 'published': 'Wed, 14 Jan 2026 00:07:50 GMT', 'summary': "Huge data centres are being built to handle AI computing but some experts say they aren't necessary.", 'source': 'BBC News'}, {'title': 'Apple turns to Google to power AI upgrade for Siri', 'link': 'https://www.bbc.com/news/articles/czdqvp2zqezo?at_medium=RSS&at_campaign=rss', 'published': 'Tue, 13 Jan 2026 13:09:19 GMT', 'summary': "Analysts say the deal is likely to be welcomed by consumers - but reflects Apple's failure to develop its own AI tools.", 'source': 'BBC News'}, {'title': 'What a new law and an investigation could mean for Grok AI deepfakes', 'link': 'https://www.bbc.com/news/articles/ckgvx88md4do?at_medium=RSS&at_campaign=rss', 'published': 'Mon, 12 Jan 2026 19:38:53 GMT', 'summary': "Elon Musk's chatbot is under fire for altering images of women to remove their clothes without their consent.", 'source': 'BBC News'}, {'title': "Ofcom investigates Elon Musk's X over Grok AI sexual deepfakes", 'link': 'https://www.bbc.com/news/articles/cwy875j28k0o?at_medium=RSS&at_campaign=rss', 'published': 'Mon, 12 Jan 2026 14:27:52 GMT', 'summary': "The watchdog said it had received reports of the platform's Grok AI chatbot creating undressed images of people.", 'source': 'BBC News'}, {'title': 'Eggie, Neo, Isaac and Memo are domestic robots. But would you let them load your dishwasher?', 'link': 'https://www.bbc.com/news/articles/clyg63e3mq4o?at_medium=RSS&at_campaign=rss', 'published': 'Mon, 12 Jan 2026 00:07:23 GMT', 'summary': 'Joe Tidy meets robots being trained to tidy up all your mess.', 'source': 'BBC News'}]

In [14]:
type(feed_results)

list

In [15]:
type(all_results)

list

In [16]:
dict = {}

dict = feed_results

In [17]:
type(dict)

list

In [18]:
df = pd.DataFrame(all_results)

In [19]:
df

,title,link,published,summary,source
0,Musk v Starmer: will UK ban X over Grok nudifi...,https://www.theguardian.com/technology/video/2...,"Tue, 13 Jan 2026 19:03:16 GMT",<p>The UK government is threatening Elon Musk’...,Technology | The Guardian
1,"Use of AI to harm women has only just begun, e...",https://www.theguardian.com/technology/2026/ja...,"Wed, 14 Jan 2026 10:00:23 GMT",<p>While Grok has introduced belated safeguard...,Technology | The Guardian
2,Google parent Alphabet hits $4tn valuation aft...,https://www.theguardian.com/technology/2026/ja...,"Mon, 12 Jan 2026 17:14:52 GMT","<p>After Apple chose Gemini to power Siri, Alp...",Technology | The Guardian
3,"The best air fryers in the UK, tried and teste...",https://www.theguardian.com/thefilter/2025/mar...,"Wed, 14 Jan 2026 10:00:11 GMT","<p>Air fryers have taken over our kitchens, bu...",Technology | The Guardian
4,The five new gadgets I tried and loved at CES ...,https://www.theguardian.com/thefilter-us/2026/...,"Tue, 13 Jan 2026 20:15:05 GMT","<p>From smartglasses to nano phone chargers, t...",Technology | The Guardian
5,Meta Plans to Cut 10% to 15% of Employees in R...,https://www.nytimes.com/2026/01/12/technology/...,"Mon, 12 Jan 2026 22:35:16 +0000",The layoffs are set to be announced this week ...,NYT > Technology
6,Apple Teams Up With Google for A.I. in Its Pro...,https://www.nytimes.com/2026/01/12/technology/...,"Mon, 12 Jan 2026 21:23:30 +0000",Apple was facing increasing questions about it...,NYT > Technology
7,Google AI Releases MedGemma-1.5: The Latest Up...,https://www.marktechpost.com/2026/01/13/google...,"Wed, 14 Jan 2026 07:30:39 +0000",<p>Google Research has expanded its Health AI ...,MarkTechPost
8,Understanding the Layers of AI Observability i...,https://www.marktechpost.com/2026/01/13/unders...,"Tue, 13 Jan 2026 14:37:15 +0000",<p>Artificial intelligence (AI) observability ...,MarkTechPost
9,Google AI Releases Universal Commerce Protocol...,https://www.marktechpost.com/2026/01/12/google...,"Tue, 13 Jan 2026 04:25:07 +0000",<p>Can AI shopping agents move beyond sending ...,MarkTechPost
10,Meet SETA: Open Source Training Reinforcement ...,https://www.marktechpost.com/2026/01/11/meet-s...,"Sun, 11 Jan 2026 15:12:24 +0000",<p>What does an end to end stack for terminal ...,MarkTechPost
11,Roblox’s AI-Powered Age Verification Is a Comp...,https://www.wired.com/story/robloxs-ai-powered...,"Tue, 13 Jan 2026 18:54:50 +0000",Kids are being identified as adults—and vice v...,WIRED
12,"Honey, I shrunk the data centres: Is small the...",https://www.bbc.com/news/articles/cd0ynenr1eno...,"Wed, 14 Jan 2026 00:07:50 GMT",Huge data centres are being built to handle AI...,BBC News
13,Apple turns to Google to power AI upgrade for ...,https://www.bbc.com/news/articles/czdqvp2zqezo...,"Tue, 13 Jan 2026 13:09:19 GMT",Analysts say the deal is likely to be welcomed...,BBC News
14,What a new law and an investigation could mean...,https://www.bbc.com/news/articles/ckgvx88md4do...,"Mon, 12 Jan 2026 19:38:53 GMT",Elon Musk's chatbot is under fire for altering...,BBC News
15,Ofcom investigates Elon Musk's X over Grok AI ...,https://www.bbc.com/news/articles/cwy875j28k0o...,"Mon, 12 Jan 2026 14:27:52 GMT",The watchdog said it had received reports of t...,BBC News
16,"Eggie, Neo, Isaac and Memo are domestic robots...",https://www.bbc.com/news/articles/clyg63e3mq4o...,"Mon, 12 Jan 2026 00:07:23 GMT",Joe Tidy meets robots being trained to tidy up...,BBC News

## Turn into a function

In [20]:
search_keywords = ["ai","artificial intelligence", "machine learning", "robot", "robots", "data science"]


def get_rss(keywords):
    # add other rss for other big news outlets itv, sky, maybe as well things like real python
    urls = ["https://www.theguardian.com/uk/technology/rss",
            "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
            "https://www.marktechpost.com/feed/",
            "https://www.wired.com/feed/rss",
            "https://openai.com/blog/rss/",
            "https://news.microsoft.com/source/topics/ai/feed/",
            "https://feeds.bbci.co.uk/news/technology/rss.xml"
            ]
    
    
    # regex pattern with word boundaries for all keywords
    pattern = re.compile(r'\b(' + '|'.join(map(re.escape, keywords)) + r')\b', re.IGNORECASE)
    
    cutoff = datetime.now() - timedelta(days=3)
    
    all_results = []  # <-- master container
    
    for url in urls:
        feed = feedparser.parse(url)
        top_ten = feed.entries[:15]
        feed_results = []
    
    
        for e in top_ten:
            if "published_parsed" not in e:
                continue
    
            pub_date = datetime.fromtimestamp(time.mktime(e.published_parsed))
    
            if pub_date > cutoff and (pattern.search(e.title or "") or pattern.search(e.summary or "")):
                feed_results.append({
                    "title": e.title,
                    "link": e.link,
                    "published": e.published,
                    "summary": e.get("summary", ""),
                    "source": feed.feed.get("title", url)
                })
    
        if feed_results:
            #all_results[url] = feed_results
            all_results.extend(feed_results)

    return all_results

In [21]:
search_keywords = ["ai","artificial intelligence", "machine learning", "robot", "robots", "data science", "grok", "openai", "chatgpt", "claude", "anthropic"]
rss_results = get_rss(search_keywords)

In [23]:
df = pd.DataFrame(rss_results)
df

,title,link,published,summary,source
0,Musk v Starmer: will UK ban X over Grok nudifi...,https://www.theguardian.com/technology/video/2...,"Tue, 13 Jan 2026 19:03:16 GMT",<p>The UK government is threatening Elon Musk’...,Technology | The Guardian
1,"Use of AI to harm women has only just begun, e...",https://www.theguardian.com/technology/2026/ja...,"Wed, 14 Jan 2026 10:00:23 GMT",<p>While Grok has introduced belated safeguard...,Technology | The Guardian
2,Google parent Alphabet hits $4tn valuation aft...,https://www.theguardian.com/technology/2026/ja...,"Mon, 12 Jan 2026 17:14:52 GMT","<p>After Apple chose Gemini to power Siri, Alp...",Technology | The Guardian
3,"The best air fryers in the UK, tried and teste...",https://www.theguardian.com/thefilter/2025/mar...,"Wed, 14 Jan 2026 10:00:11 GMT","<p>Air fryers have taken over our kitchens, bu...",Technology | The Guardian
4,The five new gadgets I tried and loved at CES ...,https://www.theguardian.com/thefilter-us/2026/...,"Tue, 13 Jan 2026 20:15:05 GMT","<p>From smartglasses to nano phone chargers, t...",Technology | The Guardian
5,Meta Plans to Cut 10% to 15% of Employees in R...,https://www.nytimes.com/2026/01/12/technology/...,"Mon, 12 Jan 2026 22:35:16 +0000",The layoffs are set to be announced this week ...,NYT > Technology
6,Apple Teams Up With Google for A.I. in Its Pro...,https://www.nytimes.com/2026/01/12/technology/...,"Mon, 12 Jan 2026 21:23:30 +0000",Apple was facing increasing questions about it...,NYT > Technology
7,Elon Musk’s X Under UK Investigation Over Grok...,https://www.nytimes.com/2026/01/12/world/europ...,"Mon, 12 Jan 2026 22:25:24 +0000",A British regulator said it had started a form...,NYT > Technology
8,Google AI Releases MedGemma-1.5: The Latest Up...,https://www.marktechpost.com/2026/01/13/google...,"Wed, 14 Jan 2026 07:30:39 +0000",<p>Google Research has expanded its Health AI ...,MarkTechPost
9,Anthropic Releases Cowork As Claude’s Local Fi...,https://www.marktechpost.com/2026/01/13/anthro...,"Tue, 13 Jan 2026 15:24:46 +0000","<p>Anthropic has released Cowork, a new featur...",MarkTechPost
10,Understanding the Layers of AI Observability i...,https://www.marktechpost.com/2026/01/13/unders...,"Tue, 13 Jan 2026 14:37:15 +0000",<p>Artificial intelligence (AI) observability ...,MarkTechPost
11,Google AI Releases Universal Commerce Protocol...,https://www.marktechpost.com/2026/01/12/google...,"Tue, 13 Jan 2026 04:25:07 +0000",<p>Can AI shopping agents move beyond sending ...,MarkTechPost
12,Meet SETA: Open Source Training Reinforcement ...,https://www.marktechpost.com/2026/01/11/meet-s...,"Sun, 11 Jan 2026 15:12:24 +0000",<p>What does an end to end stack for terminal ...,MarkTechPost
13,Roblox’s AI-Powered Age Verification Is a Comp...,https://www.wired.com/story/robloxs-ai-powered...,"Tue, 13 Jan 2026 18:54:50 +0000",Kids are being identified as adults—and vice v...,WIRED
14,"Honey, I shrunk the data centres: Is small the...",https://www.bbc.com/news/articles/cd0ynenr1eno...,"Wed, 14 Jan 2026 00:07:50 GMT",Huge data centres are being built to handle AI...,BBC News
15,Apple turns to Google to power AI upgrade for ...,https://www.bbc.com/news/articles/czdqvp2zqezo...,"Tue, 13 Jan 2026 13:09:19 GMT",Analysts say the deal is likely to be welcomed...,BBC News
16,What a new law and an investigation could mean...,https://www.bbc.com/news/articles/ckgvx88md4do...,"Mon, 12 Jan 2026 19:38:53 GMT",Elon Musk's chatbot is under fire for altering...,BBC News
17,Ofcom investigates Elon Musk's X over Grok AI ...,https://www.bbc.com/news/articles/cwy875j28k0o...,"Mon, 12 Jan 2026 14:27:52 GMT",The watchdog said it had received reports of t...,BBC News
18,"Eggie, Neo, Isaac and Memo are domestic robots...",https://www.bbc.com/news/articles/clyg63e3mq4o...,"Mon, 12 Jan 2026 00:07:23 GMT",Joe Tidy meets robots being trained to tidy up...,BBC News
19,Malaysia and Indonesia block Musk's Grok over ...,https://www.bbc.com/news/articles/cg7y10xm4x2o...,"Mon, 12 Jan 2026 05:21:33 GMT",Sexualised images of real people generated by ...,BBC News